import useChatStore from '../store/useChatStore'

export const translations = {
  es: {
    // Navigation
    navRetos: 'Retos',
    navLibreria: 'Librería',
    navProyectos: 'Proyectos',
    navComponentes: 'Componentes',
    navClases: 'Clases',
    userConfig: 'Configuraciones',
    userPerfil: 'Mi Perfil',
    userAyuda: 'Ayuda',
    userLogout: 'Cerrar sesión',

    // Visual Panel
    protoView: 'Vista Protoboard',
    protoSubtitleCircuit: 'Imagen generada por IA a partir de las coordenadas calculadas.',
    protoSubtitleNoCircuit: 'La protoboard aparecerá aquí al analizar un esquema.',
    protoLoading: 'Generando protoboard...',
    coordsTitle: 'Coordenadas utilizadas',
    coordsCopyBtn: 'Copiar todo',
    coordsColComponent: 'Componente',
    coordsColPosition: 'Conexión / Posición',
    coordsColDesc: 'Descripción',
    assemblyStepsTitle: 'Pasos de ensamblaje',
    assemblyStepOf: 'Paso {curr} de {total}',
    stepPrev: 'Anterior',
    stepNext: 'Siguiente',
    renderModeHighlight: 'Marca',
    renderModeProgressive: 'Paso',

    // Settings
    settingsTitle: 'Configuraciones',
    settingsSubtitle: 'Personaliza tu espacio de trabajo, modelos de IA y claves de acceso.',
    apiKeyTitle: 'Claves de API Personales',
    apiKeySubtitle: 'Agrega tus propias llaves. Si las dejas en blanco, se usarán las del sistema.',
    apiUsingServer: 'Usando Servidor',
    apiKeyInfoBox: 'Tus claves se guardan localmente en tu navegador de forma segura mediante LocalStorage. Nunca se almacenan en nuestros servidores.',
    settingsBtnSave: 'Guardar Cambios',
    settingsBtnDelete: 'Borrar Claves',
    confirmDeleteKeys: '¿Estás seguro de que quieres borrar tus claves de API guardadas?',
    toastSaveKeys: 'Claves de API guardadas con éxito.',
    toastDeleteKeys: 'Claves de API eliminadas.',
    providerTitle: 'Proveedor de Inteligencia Artificial',
    providerSubtitle: 'Selecciona el proveedor por defecto para procesar tus esquemas.',
    providerGeminiDesc: 'Modelo Gemini 2.5 Flash estable (Recomendado)',
    providerOpenaiDesc: 'Modelo GPT-4o original para máxima compatibilidad',
    providerLocalDesc: 'Endpoint compatible local (Ollama / LM Studio)',
    toastProviderChange: 'Proveedor cambiado a {name}.',
    prefTitle: 'Preferencias de Interfaz',
    prefSubtitle: 'Ajusta el tema visual y el idioma de la aplicación.',
    prefDarkMode: 'Modo Oscuro',
    prefDarkModeDesc: 'Cambia la paleta de colores para reducir la fatiga visual.',
    prefLang: 'Idioma de la Interfaz',
    prefLangDesc: 'Selecciona el idioma para los textos y menús de la aplicación.',
    toastLanguageChange: 'Idioma guardado correctamente.',

    // Chat Sidebar & Input
    chatNewChat: 'Nuevo Chat',
    chatHistory: 'Historial',
    chatSend: 'Enviar',
    chatPlaceholder: 'Escribe una consulta sobre tu circuito o sube una imagen...',
    chatModelLabel: 'Modelo activo',

    // Library
    libTitle: 'Librería',
    libTabTodo: 'Todo',
    libTabLibros: 'Libros',
    libTabPdfs: 'PDFs',
    libTabGuias: 'Guías',
    libTabDatasheets: 'Datasheets',
    libSearchPlaceholder: 'Buscar material...',
    libUploadBtn: 'Subir Material',
    libLoading: 'Cargando materiales...',
    libEmpty: 'No se encontraron materiales.',
    libFiltersTitle: 'Filtros por dificultad',
    libAll: 'Todos',
    libBeginner: 'Principiante',
    libIntermediate: 'Intermedio',
    libAdvanced: 'Avanzado',

    // Generic Pages
    helpTitle: 'Centro de Ayuda',
    helpSubtitle: 'Encuentra guías, tutoriales y respuestas sobre el simulador y la IA.',
    profileTitle: 'Mi Perfil',
    profileSubtitle: 'Gestiona tu información de usuario y estadísticas de aprendizaje.'
  },
  en: {
    // Navigation
    navRetos: 'Challenges',
    navLibreria: 'Library',
    navProyectos: 'Projects',
    navComponentes: 'Components',
    navClases: 'Classes',
    userConfig: 'Settings',
    userPerfil: 'My Profile',
    userAyuda: 'Help',
    userLogout: 'Log out',

    // Visual Panel
    protoView: 'Breadboard View',
    protoSubtitleCircuit: 'Image generated by AI from the calculated coordinates.',
    protoSubtitleNoCircuit: 'The breadboard will appear here once a schematic is analyzed.',
    protoLoading: 'Generating breadboard...',
    coordsTitle: 'Used Coordinates',
    coordsCopyBtn: 'Copy all',
    coordsColComponent: 'Component',
    coordsColPosition: 'Connection / Position',
    coordsColDesc: 'Description',
    assemblyStepsTitle: 'Assembly Steps',
    assemblyStepOf: 'Step {curr} of {total}',
    stepPrev: 'Previous',
    stepNext: 'Next',
    renderModeHighlight: 'Highlight',
    renderModeProgressive: 'Steps',

    // Settings
    settingsTitle: 'Settings',
    settingsSubtitle: 'Customize your workspace, AI models, and access keys.',
    apiKeyTitle: 'Personal API Keys',
    apiKeySubtitle: 'Add your own keys. If left blank, system default keys will be used.',
    apiUsingServer: 'Using Server',
    apiKeyInfoBox: 'Your keys are securely stored locally in your browser via LocalStorage. They are never saved on our servers.',
    settingsBtnSave: 'Save Changes',
    settingsBtnDelete: 'Clear Keys',
    confirmDeleteKeys: 'Are you sure you want to clear your saved API keys?',
    toastSaveKeys: 'API Keys saved successfully.',
    toastDeleteKeys: 'API Keys cleared.',
    providerTitle: 'AI Model Provider',
    providerSubtitle: 'Select the default provider to process your schematics.',
    providerGeminiDesc: 'Stable Gemini 2.5 Flash model (Recommended)',
    providerOpenaiDesc: 'Original GPT-4o model for maximum compatibility',
    providerLocalDesc: 'Local compatible endpoint (Ollama / LM Studio)',
    toastProviderChange: 'Provider changed to {name}.',
    prefTitle: 'UI Preferences',
    prefSubtitle: 'Adjust the visual theme and system language.',
    prefDarkMode: 'Dark Mode',
    prefDarkModeDesc: 'Switch color palette to reduce eye strain.',
    prefLang: 'Interface Language',
    prefLangDesc: 'Select the language for application text and menus.',
    toastLanguageChange: 'Language saved successfully.',

    // Chat Sidebar & Input
    chatNewChat: 'New Chat',
    chatHistory: 'History',
    chatSend: 'Send',
    chatPlaceholder: 'Type a query about your circuit or upload an image...',
    chatModelLabel: 'Active model',

    // Library
    libTitle: 'Library',
    libTabTodo: 'All',
    libTabLibros: 'Books',
    libTabPdfs: 'PDFs',
    libTabGuias: 'Guides',
    libTabDatasheets: 'Datasheets',
    libSearchPlaceholder: 'Search material...',
    libUploadBtn: 'Upload Material',
    libLoading: 'Loading materials...',
    libEmpty: 'No materials found.',
    libFiltersTitle: 'Filters by difficulty',
    libAll: 'All',
    libBeginner: 'Beginner',
    libIntermediate: 'Intermediate',
    libAdvanced: 'Advanced',

    // Generic Pages
    helpTitle: 'Help Center',
    helpSubtitle: 'Find guides, tutorials, and answers about the simulator and AI.',
    profileTitle: 'My Profile',
    profileSubtitle: 'Manage your user information and learning stats.'
  }
}

export function useTranslation() {
  const lang = useChatStore((s) => s.language) || 'es'
  
  const t = (key, replacements = {}) => {
    let text = translations[lang]?.[key] ?? key
    // Replace dynamic templates like {curr} or {name}
    Object.keys(replacements).forEach((k) => {
      text = text.replace(`{${k}}`, replacements[k])
    })
    return text
  }
  
  return { t, lang }
}
